// automatically generated by the FlatBuffers compiler, do not modify

package com.example.newsapp.model;

@SuppressWarnings("unused")
public final class Status {
    private Status() { }
    public static final byte APPROVED = 0;
    public static final byte REJECTED = 1;
    public static final byte PENDING = 2;

    public static final String[] names = { "APPROVED", "REJECTED", "PENDING", };

    public static String name(int e) { return names[e]; }
}

