// automatically generated by the FlatBuffers compiler, do not modify

package com.example.newsapp.model;

@SuppressWarnings("unused")
public final class Type {
  private Type() { }
  public static final byte REGULAR = 0;
  public static final byte ADMIN = 1;

  public static final String[] names = { "REGULAR", "ADMIN", };

  public static String name(int e) { return names[e]; }
}

